---
apiVersion: v1
kind: Service
metadata:
  name: watchtower-clusterip
  labels:
    app: watchtower
spec:
  ports:
  - name: watchtower
    port: 9911
    protocol: TCP
    targetPort: 9911
  selector:
    app: watchtower
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
data:
  lnd.conf: |
    # lnd configuration

    [Application Options]
    debuglevel=info
    alias=YOUR_ALIAS
   
    listen=127.0.0.1:9735
    rpclisten=127.0.0.1:10009
    restlisten=127.0.0.1:8080
    #externalip=

    [Bitcoin]
    bitcoin.active=true
    bitcoin.node=bitcoind
    bitcoin.mainnet=true

    [Bitcoind]
    bitcoind.rpcuser=changeme
    bitcoind.rpcpass=changeme
    bitcoind.rpchost=bitcoin
    bitcoind.zmqpubrawblock=tcp://bitcoin:28332
    bitcoind.zmqpubrawtx=tcp://bitcoin:28333

    [Watchtower]
    watchtower.active=true
    watchtower.listen=0.0.0.0:9911
    watchtower.towerdir=/data                            
    #watchtower.externalip=  
kind: ConfigMap
metadata:
  name: lnd-config
  namespace: stef
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watchtower
  namespace: stef
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: watchtower
  name: watchtower
  namespace: stef
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: watchtower
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: watchtower
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - args:
        - --lnddir=/data
        - --datadir=/data/data
        - --configfile=/etc/lnd/lnd.conf
        image: lsdopen/lnd:v0.11.1-beta
        name: watchtower
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 60; lncli unlock --stdin < /data/.walletpass
        volumeMounts:
        - mountPath: /data
          name: watchtower
        - mountPath: /etc/lnd
          name: lnd-config
      volumes:
      - name: watchtower
        persistentVolumeClaim:
          claimName: watchtower
      - configMap:
          defaultMode: 420
          name: lnd-config
        name: lnd-config
