apiVersion: v1
kind: Service
metadata:
  name: lndhub
  labels:
    app: lndhub
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: lndhub
---
apiVersion: v1
data:
  config.js: |
    let config = {
      bitcoind: {
        rpc: 'http://user:pass@bitcoin:8332',
      },
      redis: {
        port: 6379,
        host: 'redis-leader',
        family: 4,
        db: 0,
      },
      lnd: {
        url: 'lnd-clusterip:10009',
        password: '',
      },
    };

    if (process.env.CONFIG) {
      console.log('using config from env');
      config = JSON.parse(process.env.CONFIG);
    }

    module.exports = config;
kind: ConfigMap
metadata:
  name: lndhub-config
  namespace: stef
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: lndhub
  name: lndhub
  namespace: stef
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lndhub
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lndhub
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - image: lsdopen/lndhub:v1.2.0
        name: lndhub
        imagePullPolicy: Always
        command: ['npm']
        args: ['start', '--prefix', '/lndhub']
        # command: ['sleep']
        # args: ['infinity']
        volumeMounts:
        - mountPath: /lndhub/config.js
          subPath: "config.js"
          name: lndhub-config
        - name: lnd-admin-macaroon
          subPath: "admin.macaroon"
          mountPath: "/lndhub/admin.macaroon"
          readOnly: true
        - name: lnd-tls-cert
          subPath: "tls.cert"
          mountPath: "/lndhub/tls.cert"
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 0420
          name: lndhub-config
        name: lndhub-config
      - name: lnd-admin-macaroon
        secret:
          secretName: lndhub
      - name: lnd-tls-cert
        secret:
          secretName: lndhub